version: "3.7"

# yaml refs
x-refs:
  common_config: &common_config
    restart: always
    env_file:
    - .env
    logging:
      driver: gcplogs
      options: 
        gcp-project: ${GCP_PROJECT}

services:
  postgres:
    restart: always
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  auth:
    <<: *common_config
    build: 
      context: ./services/auth
      dockerfile: Dockerfile_dev
      network: host
    ports:
    - "9000"
    depends_on:
      - postgres
    volumes:
      - ./services/auth/src:/usr/src/app/src
      - ./certs/google-cert.json:/google-cert.json

    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB} 
      DATA_HOST: http://data:8080
      GOOGLE_APPLICATION_CREDENTIALS: /google-cert.json

  data:
    <<: *common_config
    image: hasura/graphql-engine:v1.2.0-beta.4.cli-migrations-v2
    volumes:
      - ./services/data/migrations:/hasura-migrations
      - ./services/data/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - postgres
      - events
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations"
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
      EVENT_TRIGGER_URL: http://events:9000/events
      REMOTE_SCHEMA_URL: http://events:9000/graphql
      ACTION_URL: http://events:9000/actions
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:9000/verify
      
  events:
    <<: *common_config
    build: 
      context: ./services/events
      dockerfile: Dockerfile_dev
      network: host
    ports:
    - "9000"
    depends_on:
      - postgres
    volumes:
      - ./services/events/src:/usr/src/app/src
      - ./certs/google-cert.json:/google-cert.json

    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB} 
      DATA_HOST: http://data:8080
      GOOGLE_APPLICATION_CREDENTIALS: /google-cert.json
      

volumes:
  db_data:
