version: "3.7"

# yaml refs
x-refs:
  common_config: &common_config
    restart: always
    env_file:
    - .env

services:

  postgres:
    restart: always
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  data:
    <<: *common_config
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    volumes:
      - ./services/data/migrations:/hasura-migrations
      - ./services/data/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations"
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "${FIREBASE_PROJECT_ID}", "issuer": "https://securetoken.google.com/${FIREBASE_PROJECT_ID}"}'

      
volumes:
  db_data:
